# Generated by Django 5.0.6 on 2024-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='cust_id',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
