# Generated by Django 5.0.6 on 2024-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderplaced_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='cust_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
